In [1]:
def X_Taken_students(df_ , Subj):
    new_df = pd.DataFrame(columns=['ID','Student_Level','Subj','Section'])
    rowCount=len(df_.index)
    for i in range (rowCount):
        if(df_.iat[i,2]== Subj):
            id_stu=df_.iat[i,0]
            for k in range (rowCount):
                if(i != k and df_.iat[k,0]==id_stu):
                    new_df=new_df.append(df_.loc[[k]],ignore_index=True) 
    new_df=new_df.sort_values('Subj')
    new_df=new_df.reset_index(drop=True)                
    return new_df

def Classes_Students(new_df_):           
    list_sub_nms=[]                      #dictinary mi yapsam?
    list_ppl_count=[]
    prev=''

    for i in range (len(new_df_)):
        x= new_df_.iat[i,2]
        if(x != prev):
            list_sub_nms.append(x)
            list_ppl_count.append(1)
            prev=x
        else:
            temp=list_sub_nms.index(x)
            list_ppl_count[temp]=list_ppl_count[temp]+1

    Combiined_List= pd.DataFrame ({'Subj': list_sub_nms,'Total_Students':list_ppl_count})
    Combiined_List=Combiined_List.sort_values('Total_Students',ascending=False)
    Combiined_List=Combiined_List.reset_index(drop=True)
    return Combiined_List

In [2]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

file = r'C:\Users\umut\Desktop\Proje\FirstPart_200801.xlsx'
df = pd.read_excel(file, sheet_name='Sheet1')

df=df.drop(columns=['Term','Max Capacity','Enrollment'])

df['Subj'] =df['Subj'].astype(str) + ' ' + df['Numb'].astype(str) #delete space
df.drop(columns=['Numb'],inplace=True)

sort_by_ID=df.sort_values('ID')
sort_by_ID=sort_by_ID.reset_index(drop=True)

In [5]:
file = r'C:\Users\umut\Desktop\Proje\FirstPart_200801.xlsx'
df_Enr = pd.read_excel(file, sheet_name='Sheet1')

df_Enr=df_Enr.drop(columns=['Term','ID','Student_Level','Max Capacity'])

df_Enr['Subj'] =df_Enr['Subj'].astype(str) + ' ' + df_Enr['Numb'].astype(str) #delete space
df_Enr.drop(columns=['Numb'],inplace=True)

df_Enr=df_Enr.sort_values(by=['Subj', 'Section'])
df_Enr=df_Enr.reset_index(drop=True)



R_Count=len(subj_nm)                  #TO MAKE THIS WORK FOR DIFFERENT TERMS, YOU SHOULD ALSO ADD TERMS 
array_St_Enr=[0 for x in range (R_Count)]
temp_sec=''

#since most columns are same you can use like group by!!

for i in range (R_Count):
       #find index of first subj_nm[i]          , k=index             , to make it faster you might start where it left
        
        for t in range (len(df_Enr)):
            if(df_Enr.iat[t,0]==subj_nm[i]):
                k=t
                break
        
        while(subj_nm[i]==df_Enr.iat[k,0]):
            if(temp_sec != df_Enr.iat[k,1]):   #add to the array_st_enr
                temp_sec =  df_Enr.iat[k,1]
                array_St_Enr[i] = array_St_Enr[i] + df_Enr.iat[k,2]
                
            k=k+1
            if(k==len(df_Enr)):
                break

        temp_sec=''

#| Rem_class["Total_Students"] / Rem_Class["Subj"] > 0.2 ]

In [3]:
sort_by_Subj=df.sort_values('Subj')                         #subj_nm  => names of subjects
subj_nm=[sort_by_Subj.iat[0,2]]
prev=subj_nm[0]
rowCount=len(df.index)

for i in range (rowCount):
    if(prev != sort_by_Subj.iat[i,2]):
        prev=sort_by_Subj.iat[i,2]
        subj_nm.append(prev)

In [4]:
def isInside(CL,p):
    for i in range (len(CL)):
        k=0
        while(p[k] in CL[i]):
            k=k+1
            if(k==len(p)):
                return True
    return False     

Clusters=[]    #in cluster append => example: Clusters=[[1,2,8],[1,3],[1,4]]    if you try to add 4,1 or 1,8 it should NOT add!! 


def RecursiveFunc(b_subj,pth,df_f):
    
    pth.append(subj_nm.index(b_subj))
    
    b_df = X_Taken_students(df_f , b_subj)
    Rem_Class= Classes_Students(b_df)
    Rem_Class= Rem_Class[Rem_Class["Total_Students"] > 10] 
                                                             #Remove rows which has less than 10 students  ,Adjust % for terms
    Rem_Class= Rem_Class.reset_index(drop=True)              #DONT FORGET to add % with or cond. to upper line

    if(len(Rem_Class.index)== 0 or len(pth)== 10):           #If none left in Rem_Class or pth length reached 10 quit recursion
        #dont continue
        if(len(pth)!=1 or not isInside(Clusters,pth)):
            Clusters.append(pth)                             #add path to Clusters       ### Check if exists though ###
    
    else:
        for t in range (len(Rem_Class.index)):
            RecursiveFunc(Rem_Class.iat[t,0],pth,b_df)
            
    return
        


for i in range (len(subj_nm)):
    base_subj = subj_nm[i]
    path=[]
    
    RecursiveFunc(base_subj,path,df)
        
        
Clusters

KeyboardInterrupt:

In [7]:
df

          ID Student_Level     Subj Section
0       9194            UG  ACC 301       0
1       9208            UG  ACC 301       0
2       9233            UG  ACC 301       0
3       9410            UG  ACC 301       0
4       9416            UG  ACC 301       0
5       9426            UG  ACC 301       0
6       9529            UG  ACC 301       0
7       9552            UG  ACC 301       0
8       9680            UG  ACC 301       0
9       9696            UG  ACC 301       0
10      9748            UG  ACC 301       0
11      9781            UG  ACC 301       0
12      9820            UG  ACC 301       0
13      9870            UG  ACC 301       0
14      9884            UG  ACC 301       0
15      9893            UG  ACC 301       0
16      9909            UG  ACC 301       0
17      9968            UG  ACC 301       0
18      9972            UG  ACC 301       0
19      9974            UG  ACC 301       0
20      9991            UG  ACC 301       0
21      9993            UG  ACC 301       0
22     10007            UG  ACC 301       0
23     10038            UG  ACC 301       0
24     10090            UG  ACC 301       0
25     10100            UG  ACC 301       0
26     10178            UG  ACC 301       0
27     10179            UG  ACC 301       0
28     10288            UG  ACC 301       0
29     10315            UG  ACC 301       0
...      ...           ...      ...     ...
24702  12592            SP   VA 545       0
24703  12593            SP   VA 545       0
24704   9283            MA   VA 591       0
24705  11157            MA   VA 591       0
24706  11164            MA   VA 591       0
24707  11173            MA   VA 591       0
24708  11176            MA   VA 591       0
24709   9015            MA   VA 599       0
24710   9087            MA   VA 599       0
24711   9283            MA   VA 599       0
24712   9377            MA   VA 599       0
24713  10476            MA   VA 599       0
24714  11157            MA   VA 599       0
24715  11164            MA   VA 599       0
24716  11173            MA   VA 599       0
24717  11176            MA   VA 599       0
24718   9161            UG  VIS 310       0
24719   9277            UG  VIS 310       0
24720   9789            UG  VIS 310       0
24721   9876            UG  VIS 310       0
24722   9933            UG  VIS 310       0
24723  11945            XU  VIS 310       0
24724   9165            DR  VIS 510       0
24725   9322            SP  VIS 510       0
24726   9377            MA  VIS 510       0
24727   9610            SP  VIS 510       0
24728   9787            SP  VIS 510       0
24729  11152            MA  VIS 510       0
24730  11164            MA  VIS 510       0
24731  12613            MA  VIS 510       0

[24732 rows x 4 columns]

In [8]:
X_Taken_students(df,'CS 201')

         ID Student_Level      Subj Section
0     10768            UG   ARA 301       A
1     10091            UG   ARA 301       A
2     11486            UG   BIO 332       0
3     11486            UG  BIO 332L       0
4      9320            UG   CIP 101       A
5     10991            UG   CIP 101       B
6     10015            UG   CIP 101       B
7     11638            UG   CIP 101       A
8     11368            UG   CIP 101       B
9     11422            UG   CIP 101       B
10    11501            UG   CIP 101       B
11    10353            UG   CIP 101       B
12    11743            UG   CIP 101       B
13    11909            UG   CIP 101       B
14    11765            UG   CIP 101       B
15    11298            UG   CIP 101       A
16     9271            UG   CIP 101       B
17     9667            UG   CIP 101       B
18    11291            UG   CIP 101       A
19    10266            UG   CIP 101       B
20    10768            UG   CIP 101       B
21    10779            UG   CIP 101       A
22    10998            UG   CIP 101       B
23    10846            UG   CIP 101       A
24    11359            UG   CIP 101       B
25    10958            UG   CIP 101       B
26    11653            UG   CIP 101       B
27    11907            UG   CIP 101       B
28    10895            UG   CIP 101       B
29    10896            UG   CIP 101       B
...     ...           ...       ...     ...
3491  10231            UG   TLL 101      A5
3492  10935            UG   TLL 101      D3
3493  11210            UG   TLL 101      C7
3494  10604            UG   TLL 101      C6
3495  10266            UG   TLL 101      A5
3496  10584            UG   TLL 101      A7
3497  10896            UG   TLL 101      C8
3498  11408            UG   TLL 101      A1
3499  10496            UG   TLL 101      A6
3500  11417            UG   TLL 101      C9
3501  10930            UG   TLL 101      C6
3502  10801            UG   TLL 101      A4
3503  10958            UG   TLL 101      A9
3504  11056            UG   TLL 101      D1
3505  11086            UG   TLL 301       0
3506  11368            UG    VA 201       B
3507  11367            UG    VA 201       B
3508  11600            UG    VA 201       B
3509  11527            UG    VA 201       B
3510  11415            UG    VA 201       A
3511  11527            UG    VA 203       A
3512  11367            UG    VA 203       A
3513  11689            UG    VA 203       B
3514  11390            UG    VA 203       B
3515  11415            UG    VA 203       A
3516  11415            UG    VA 215       0
3517  10867            UG    VA 333       0
3518  10833            UG    VA 333       0
3519  11063            UG    VA 333       0
3520  11071            UG    VA 335       0

[3521 rows x 4 columns]