In [1]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

file = r'C:\Users\umut\Desktop\Proje\FirstPart_200801.xlsx'
df = pd.read_excel(file, sheet_name='Sheet1')

df=df.drop(columns=['Term','Max Capacity','Enrollment'])

df['Subj'] =df['Subj'].astype(str) + ' ' + df['Numb'].astype(str) #delete space
df.drop(columns=['Numb'],inplace=True)

sort_by_ID=df.sort_values('ID')
sort_by_ID=sort_by_ID.reset_index(drop=True)

df

          ID Student_Level     Subj Section
0       9194            UG  ACC 301       0
1       9208            UG  ACC 301       0
2       9233            UG  ACC 301       0
3       9410            UG  ACC 301       0
4       9416            UG  ACC 301       0
5       9426            UG  ACC 301       0
6       9529            UG  ACC 301       0
7       9552            UG  ACC 301       0
8       9680            UG  ACC 301       0
9       9696            UG  ACC 301       0
10      9748            UG  ACC 301       0
11      9781            UG  ACC 301       0
12      9820            UG  ACC 301       0
13      9870            UG  ACC 301       0
14      9884            UG  ACC 301       0
15      9893            UG  ACC 301       0
16      9909            UG  ACC 301       0
17      9968            UG  ACC 301       0
18      9972            UG  ACC 301       0
19      9974            UG  ACC 301       0
20      9991            UG  ACC 301       0
21      9993            UG  ACC 301       0
22     10007            UG  ACC 301       0
23     10038            UG  ACC 301       0
24     10090            UG  ACC 301       0
25     10100            UG  ACC 301       0
26     10178            UG  ACC 301       0
27     10179            UG  ACC 301       0
28     10288            UG  ACC 301       0
29     10315            UG  ACC 301       0
...      ...           ...      ...     ...
24702  12592            SP   VA 545       0
24703  12593            SP   VA 545       0
24704   9283            MA   VA 591       0
24705  11157            MA   VA 591       0
24706  11164            MA   VA 591       0
24707  11173            MA   VA 591       0
24708  11176            MA   VA 591       0
24709   9015            MA   VA 599       0
24710   9087            MA   VA 599       0
24711   9283            MA   VA 599       0
24712   9377            MA   VA 599       0
24713  10476            MA   VA 599       0
24714  11157            MA   VA 599       0
24715  11164            MA   VA 599       0
24716  11173            MA   VA 599       0
24717  11176            MA   VA 599       0
24718   9161            UG  VIS 310       0
24719   9277            UG  VIS 310       0
24720   9789            UG  VIS 310       0
24721   9876            UG  VIS 310       0
24722   9933            UG  VIS 310       0
24723  11945            XU  VIS 310       0
24724   9165            DR  VIS 510       0
24725   9322            SP  VIS 510       0
24726   9377            MA  VIS 510       0
24727   9610            SP  VIS 510       0
24728   9787            SP  VIS 510       0
24729  11152            MA  VIS 510       0
24730  11164            MA  VIS 510       0
24731  12613            MA  VIS 510       0

[24732 rows x 4 columns]

In [2]:
new_df = pd.DataFrame(columns=['ID','Student_Level','Subj','Section'])
rowCount=len(df.index)
for i in range (rowCount):
    if(df.iat[i,2]=='MATH 101'):
        id_stu=df.iat[i,0]
        for k in range (rowCount):
            if(i != k and df.iat[k,0]==id_stu):
                new_df=new_df.append(df.loc[[k]],ignore_index=True) 
                
new_df

         ID Student_Level       Subj Section
0      9121            UG    CIP 101       B
1      9121            UG   HART 414       0
2      9121            UG  MATH 101R      A8
3      9121            UG    SPS 303       A
4      9121            UG   SPS 303D      A7
5      9121            UG     VA 335       0
6      9121            UG     VA 401       C
7      9168            UG   ECON 320       0
8      9168            UG   ECON 330       0
9      9168            UG   ECON 405       0
10     9168            UG  ECON 330R       0
11     9168            UG   MATH 203       B
12     9168            UG  MATH 101R      A7
13     9168            UG  MATH 203R      B1
14     9170            UG    ENS 208       0
15     9170            UG   ENS 208R      A5
16     9170            UG  MATH 101R      A2
17     9170            UG   MGMT 201       B
18     9170            UG  MGMT 201R      B4
19     9170            UG     NS 101       B
20     9170            UG    NS 101R      B1
21     9225            UG   ECON 202       C
22     9225            UG  ECON 202R      C1
23     9225            UG    ENS 208       0
24     9225            UG   ENS 208R      A5
25     9225            UG    HUM 201       A
26     9225            UG   MATH 201       0
27     9225            UG  MATH 101R      A2
28     9225            UG  MATH 201R      A8
29     9229            UG    ARA 301       A
...     ...           ...        ...     ...
4501  12509            UG   SPS 101D     A13
4502  12509            UG    TLL 101      B5
4503  12513            UG    CIP 101       A
4504  12513            UG    ENG 101      A1
4505  12513            UG   HIST 191       A
4506  12513            UG  MATH 101R      B1
4507  12513            UG     NS 101       B
4508  12513            UG    NS 101R      B2
4509  12513            UG    SPS 101       A
4510  12513            UG   SPS 101D     A13
4511  12513            UG    TLL 101      B8
4512  12514            UG    CIP 101       A
4513  12514            UG    ENG 101      A3
4514  12514            UG   HIST 191       B
4515  12514            UG  MATH 101R      B4
4516  12514            UG     NS 101       A
4517  12514            UG    NS 101R      A3
4518  12514            UG   PROJ 102       0
4519  12514            UG    SPS 101       A
4520  12514            UG   SPS 101D     A15
4521  12514            UG    TLL 101      A4
4522  12518            UG    CIP 101       A
4523  12518            UG    ENG 101      A6
4524  12518            UG   HIST 191       B
4525  12518            UG  MATH 101R      B5
4526  12518            UG     NS 101       A
4527  12518            UG    NS 101R      A4
4528  12518            UG    SPS 101       A
4529  12518            UG   SPS 101D     A16
4530  12518            UG    TLL 101      A5

[4531 rows x 4 columns]

In [17]:
#her dersin kaçar kişi almış?
new_df=new_df.sort_values('Subj')
new_df=new_df.reset_index(drop=True)
new_df

         ID Student_Level     Subj Section
0      9059            UG  ARA 301       B
1      9229            UG  ARA 301       A
2     12119            UG  CIP 101       A
3     12394            UG  CIP 101       B
4     11403            UG  CIP 101       B
5     12121            UG  CIP 101       A
6     12123            UG  CIP 101       A
7     12399            UG  CIP 101       A
8     12125            UG  CIP 101       A
9     12126            UG  CIP 101       B
10    12128            UG  CIP 101       B
11    12148            UG  CIP 101       B
12    10771            UG  CIP 101       A
13    12155            UG  CIP 101       A
14    12061            UG  CIP 101       A
15    12052            UG  CIP 101       A
16     9121            UG  CIP 101       B
17    12051            UG  CIP 101       B
18    12353            UG  CIP 101       B
19    11735            UG  CIP 101       A
20    11525            UG  CIP 101       A
21    12370            UG  CIP 101       A
22    11524            UG  CIP 101       A
23    11760            UG  CIP 101       A
24    12102            UG  CIP 101       B
25    11519            UG  CIP 101       A
26    12106            UG  CIP 101       A
27    12088            UG  CIP 101       B
28    12113            UG  CIP 101       B
29    11412            UG  CIP 101       B
...     ...           ...      ...     ...
4501  10445            UG   VA 201       A
4502  10452            UG   VA 201       A
4503  10018            UG   VA 201       A
4504  10452            UG   VA 203       B
4505  10566            UG   VA 203       A
4506  11539            UG   VA 203       A
4507  10445            UG   VA 203       A
4508  11716            UG   VA 203       A
4509  11580            UG   VA 203       A
4510  10322            UG   VA 203       A
4511  10311            UG   VA 215       0
4512   9327            UG   VA 215       0
4513  10291            UG   VA 215       0
4514  12461            UG   VA 215       0
4515  10311            UG   VA 301       0
4516   9327            UG   VA 301       0
4517   9262            UG   VA 331       0
4518   9223            UG   VA 331       0
4519   9365            UG   VA 332       A
4520   9327            UG   VA 332       A
4521  10311            UG   VA 332       A
4522  10415            UG   VA 333       0
4523   9121            UG   VA 335       0
4524  10415            UG   VA 401       A
4525   9121            UG   VA 401       C
4526   9059            UG   VA 401       B
4527   9223            UG   VA 401       A
4528   9365            UG   VA 401       B
4529  10415            UG   VA 431       0
4530   9327            UG   VA 439       0

[4531 rows x 4 columns]

In [22]:
list_sub_nms=[]                      #dictinary mi yapsam?
list_ppl_count=[]
prev=''

for i in range (len(new_df)):
    x= new_df.iat[i,2]
    if(x != prev):
        list_sub_nms.append(x)
        list_ppl_count.append(1)
        prev=x
    else:
        temp=list_sub_nms.index(x)
        list_ppl_count[temp]=list_ppl_count[temp]+1
        
Combiined_List= pd.DataFrame ({'Subj': list_sub_nms,'Total_Students':list_ppl_count})
Combiined_List=Combiined_List.sort_values('Total_Students',ascending=False)
Combiined_List=Combiined_List.reset_index(drop=True)
Combiined_List

         Subj  Total_Students
0   MATH 101R             521
1     NS 101R             477
2      NS 101             477
3    SPS 101D             473
4     SPS 101             473
5     TLL 101             471
6    HIST 191             470
7     ENG 101             434
8     CIP 101             244
9    PROJ 102             172
10     NS 102              20
11    NS 102R              20
12    RUS 101              18
13  MGMT 201R              14
14   MGMT 201              14
15  ECON 202R              13
16   ECON 202              13
17    SPA 101              12
18     VA 203               7
19  ECON 204R               7
20   ECON 204               7
21   MGMT 202               6
22  MGMT 202R               6
23   POLS 251               5
24     VA 401               5
25     CS 201               5
26   ECON 201               5
27     VA 201               5
28    CS 201R               5
29   CULT 201               5
..        ...             ...
57    ARA 301               2
58    GER 201               2
59    HUM 212               2
60   FILM 331               2
61   HART 414               2
62   HART 425               2
63   HART 433               2
64   CULT 391               2
65   HUM 212D               2
66    LIT 394               2
67    CIP 102               2
68     VA 335               1
69     VA 333               1
70   ECON 405               1
71   CULT 434               1
72   ECON 320               1
73   ECON 330               1
74     VA 431               1
75  ECON 330R               1
76   MGMT 409               1
77    ENS 315               1
78    FRE 101               1
79  MATH 306R               1
80   HIST 349               1
81   HIST 485               1
82    HUM 201               1
83    HUM 206               1
84    LIT 440               1
85   MATH 306               1
86     VA 439               1

[87 rows x 2 columns]

In [23]:
#denememe devam ediyorum, şimdide en üsttekini alanları seçmiş olıyım ama zaten 
#reciti olduğu için aynı olucak bir kere daha devam etmişim sayıyorum

asama2 = pd.DataFrame(columns=['ID','Student_Level','Subj','Section'])
rowCount2=len(new_df.index)
for i in range (rowCount2):
    if(new_df.iat[i,2]=='NS 101'):
        id_st=new_df.iat[i,0]
        for k in range (rowCount2):
            if(i != k and new_df.iat[k,0]==id_st):
                asama2=asama2.append(new_df.loc[[k]],ignore_index=True) 
                
asama2

         ID Student_Level       Subj Section
0      9607            UG    ENG 101      C2
1      9607            UG  MATH 101R      B3
2      9607            UG    NS 101R     A11
3      9607            UG    SPS 101       B
4      9607            UG   SPS 101D      B4
5      9607            UG    TLL 101      A5
6     10946            UG    ENG 101      A2
7     10946            UG   HIST 191       B
8     10946            UG  MATH 101R      B3
9     10946            UG    NS 101R      B4
10    10946            UG   PROJ 102       0
11    10946            UG    SPS 101       B
12    10946            UG   SPS 101D     B18
13    10946            UG    TLL 101      A2
14    12448            UG    CIP 101       A
15    12448            UG   HIST 191       A
16    12448            UG  MATH 101R      A1
17    12448            UG    NS 101R      B6
18    12448            UG    SPS 101       B
19    12448            UG   SPS 101D     B15
20    12448            UG    TLL 101      B2
21    10655            UG   HIST 191       B
22    10655            UG  MATH 101R      B5
23    10655            UG    NS 101R     B12
24    10655            UG   POLS 251       A
25    10655            UG    SPS 101       B
26    10655            UG   SPS 101D      B5
27    10655            UG    TLL 101      A5
28    12447            UG    CIP 101       A
29    12447            UG    ENG 101      A1
...     ...           ...        ...     ...
3700  12052            UG   HIST 191       A
3701  12052            UG  MATH 101R      A5
3702  12052            UG    NS 101R      A3
3703  12052            UG   PROJ 102       0
3704  12052            UG    SPS 101       A
3705  12052            UG   SPS 101D     A11
3706  12052            UG    TLL 101      A3
3707  11524            UG    CIP 101       A
3708  11524            UG    ENG 101      C7
3709  11524            UG   HIST 191       B
3710  11524            UG  MATH 101R      B7
3711  11524            UG    NS 101R      B9
3712  11524            UG    SPS 101       B
3713  11524            UG   SPS 101D      B9
3714  11524            UG    TLL 101      B7
3715  12106            UG    CIP 101       A
3716  12106            UG    ENG 101      C5
3717  12106            UG   HIST 191       B
3718  12106            UG  MATH 101R      A1
3719  12106            UG    NS 101R     A11
3720  12106            UG    SPS 101       B
3721  12106            UG   SPS 101D      B1
3722  12106            UG    TLL 101      B8
3723  11781            UG    ENG 101      B7
3724  11781            UG   HIST 191       A
3725  11781            UG  MATH 101R      A3
3726  11781            UG    NS 101R      A5
3727  11781            UG    SPS 101       A
3728  11781            UG   SPS 101D     A11
3729  11781            UG    TLL 101      B4

[3730 rows x 4 columns]

In [25]:
asama2=asama2.sort_values('Subj')
asama2=asama2.reset_index(drop=True)

list_sub_nms2=[]                      #dictinary mi yapsam?
list_ppl_count2=[]
prev2=''

for i in range (len(asama2)):
    x2= asama2.iat[i,2]
    if(x2 != prev2):
        list_sub_nms2.append(x2)
        list_ppl_count2.append(1)
        prev2=x2
    else:
        temp2=list_sub_nms2.index(x2)
        list_ppl_count2[temp2]=list_ppl_count2[temp2]+1
        
Combiined_List2= pd.DataFrame ({'Subj': list_sub_nms2,'Total_Students':list_ppl_count2})
Combiined_List2=Combiined_List2.sort_values('Total_Students',ascending=False)
Combiined_List2=Combiined_List2.reset_index(drop=True)
Combiined_List2

         Subj  Total_Students
0   MATH 101R             477
1     NS 101R             477
2     SPS 101             464
3    SPS 101D             464
4     TLL 101             463
5    HIST 191             462
6     ENG 101             427
7     CIP 101             235
8    PROJ 102             172
9     RUS 101              14
10    SPA 101               9
11  MGMT 201R               6
12     VA 203               6
13   MGMT 201               6
14   CULT 201               4
15    GER 101               4
16   ECON 204               3
17     VA 201               3
18  ECON 204R               3
19    CIP 102               2
20   POLS 251               2
21     VA 215               2
22   HUM 202D               2
23    HUM 202               2
24    GER 201               2
25   ECON 202               2
26  ECON 202R               2
27    IR 201D               1
28    ENS 208               1
29     CS 201               1
30    CS 201R               1
31   ECON 201               1
32  ECON 201R               1
33   POLS 473               1
34   ENS 208R               1
35    JAP 101               1
36   POLS 352               1
37   HART 425               1
38  MGMT 202R               1
39   MGMT 202               1
40   HART 433               1
41     IR 201               1

In [ ]:
def XSubj_Taken(df_ , Subj):
    new_df = pd.DataFrame(columns=['ID','Student_Level','Subj','Section'])
    rowCount=len(df_.index)
    for i in range (rowCount):
        if(df_.iat[i,2]== Subj):
            id_stu=df_.iat[i,0]
            for k in range (rowCount):
                if(i != k and df_.iat[k,0]==id_stu):
                    new_df=new_df.append(df.loc[[k]],ignore_index=True) 
    new_df=new_df.sort_values('Subj')
    new_df=new_df.reset_index(drop=True)                
    return new_df

def func(new_df_):
    list_sub_nms=[]                      #dictinary mi yapsam?
    list_ppl_count=[]
    prev=''

    for i in range (len(new_df_)):
        x= new_df_.iat[i,2]
        if(x != prev):
            list_sub_nms.append(x)
            list_ppl_count.append(1)
            prev=x
        else:
            temp=list_sub_nms.index(x)
            list_ppl_count[temp]=list_ppl_count[temp]+1

    Combiined_List= pd.DataFrame ({'Subj': list_sub_nms,'Total_Students':list_ppl_count})
    Combiined_List=Combiined_List.sort_values('Total_Students',ascending=False)
    Combiined_List=Combiined_List.reset_index(drop=True)
    return Combiined_List